# 수업에 사용될 라이브러리 설치

In [1]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 8A08-8DB8

 C:\Users\smile\OneDrive\coding\python\study\(inflearn)DeepingSauce\quant_investing_part1 디렉터리

2022-11-08  오후 01:20    <DIR>          .
2022-11-08  오후 01:20    <DIR>          ..
2022-11-08  오후 01:23             6,670 #2.1 library&numpy.ipynb
2022-11-08  오후 12:12             8,364 #2.2 Series.ipynb
2022-11-08  오후 12:52            30,556 #2.3 DataFrame.ipynb
2022-11-08  오후 12:15    <DIR>          .ipynb_checkpoints
2022-11-08  오후 01:20                 0 test.py
               4개 파일              45,590 바이트
               3개 디렉터리  76,467,965,952 바이트 남음


# Numpy 소개

In [2]:
import numpy as np

## ndarray dtype

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# indexing이 list와 방식이 같음
a[0]

1

- append() 같은 함수가 없음 -> 즉, python의 list와는 다른 data type임

## Universal function

In [ ]:
a = [1,2,3]
b = [4,5,6]

new_list = []
for e1, e2 in zip(a,b):
    new_list.append(e1+e2)
new_list

[5, 7, 9]

In [ ]:
a+b

[1, 2, 3, 4, 5, 6]

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
a+b

array([5, 7, 9])

In [ ]:
a = np.array(
    [
        [1,2],
        [3,4]
    ]
)

In [ ]:
a[0]

array([1, 2])

In [ ]:
a[0][1]

2